class_name ChiselVariations
extends RefCounted

# Chisel (team.chisel, GTNH's bundled 2.12.3 build) hardcodes its meta -> texture mapping
# directly in Java bytecode (team.chisel.Features$N.addBlocks(), one anonymous subclass per
# block group, each calling CarvableHelper.addVariation(descKey, meta, texturePath)) -- there
# is no blockstate JSON or config file to read at runtime (see GTNHExtension._heal_chisel).
# This table was extracted once by decompiling every Features$N.class with javap and parsing
# the addVariation calls (script kept out of the repo; see .plans/ if it needs regenerating
# against a different Chisel build). Values are the texture's base name relative to
# assets/chisel/textures/blocks/, exactly as Chisel's own code passes it -- resolving that to
# an actual file (bare / group-prefixed / side+top pair / ctmv|ctmh+top pair) is
# GTNHExtension's job, not this table's; this is pure ground-truth data, not a guess.
#
# A handful of groups are deliberately excluded, not guessed at: metalOre, voidstone and
# tallow reuse the exact same lang/desc key text across what decompiling showed are multiple
# DIFFERENT underlying block registries (metalOre: 11 different ore metals; voidstone: an
# animated/static texture pair) or genuinely conflicting values with no way to disambiguate
# from the bytecode alone -- binding either the wrong texture or a phantom registry that may
# not exist would be worse than leaving them dropped, same as an unhealed import.

const VARIATIONS := {
	"andesite": {
		0: "andesite/andesite",
		1: "andesite/andesitePolished",
		2: "andesite/andesitePillar",
		3: "andesite/andesiteLBrick",
		4: "andesite/andesiteOrnate",
		5: "andesite/andesitePrism",
		6: "andesite/andesiteTiles",
	},
	# Registered through team.chisel.client.render.SubmapManagerAntiblock, keyed by dye NAME (not
	# index) at both the desc and texture ends: Features$6.addBlocks() builds "tile.antiBlock." +
	# ItemDye.field_150921_b[i] + ".desc" and constructs the submap with field_150921_b[i] itself,
	# which SubmapManagerAntiblock.registerIcons() turns into "chisel:antiblock/<name>-antiBlock"
	# (getBaseIcon() returns that whole registered icon verbatim -- no cropping -- so the plain
	# 32x32 file IS the flat appearance; the same-named "-antiBlock-ctm" file is only the extra
	# connected-texture sheet). field_150921_b is 1.7.10's well-documented ItemDye.dyeColorNames
	# order (Ink Sac=0 .. Bone Meal=15) -- NOT the wool/carpet meta order the rest of this file's
	# color tables use -- confirmed against the jar's own 16 antiblock/*-antiBlock.png files and
	# their name-keyed en_US.lang descs (tile.antiBlock.<name>.desc, not <group>.<meta>.desc, so
	# _heal_chisel's generic "<group> <meta>" fallback names these instead of the real desc text).
	"antiBlock": {
		0: "antiblock/black-antiBlock",
		1: "antiblock/red-antiBlock",
		2: "antiblock/green-antiBlock",
		3: "antiblock/brown-antiBlock",
		4: "antiblock/blue-antiBlock",
		5: "antiblock/purple-antiBlock",
		6: "antiblock/cyan-antiBlock",
		7: "antiblock/silver-antiBlock",
		8: "antiblock/gray-antiBlock",
		9: "antiblock/pink-antiBlock",
		10: "antiblock/lime-antiBlock",
		11: "antiblock/yellow-antiBlock",
		12: "antiblock/light_blue-antiBlock",
		13: "antiblock/magenta-antiBlock",
		14: "antiblock/orange-antiBlock",
		15: "antiblock/white-antiBlock",
	},
	"arcane": {
		0: "arcane/moonEngrave",
		1: "arcane/moonGlowAnim",
		2: "arcane/arcaneTile",
		3: "arcane/runes",
		4: "arcane/runesGlow",
		5: "arcane/bigBrick",
		6: "arcane/conduitGlowAnim",
		7: "arcane/BorderBrain",
		8: "arcane/ArcaneBorder",
		9: "arcane/arcaneMatrix",
		10: "arcane/thaumcraftLogo",
		11: "arcane/arcaneCrackAnim",
	},
	"bloodRune": {
		0: "bloodMagic/bloodRuneArranged",
		1: "bloodMagic/bloodRuneBricks",
		2: "bloodMagic/bloodRuneCarved",
		3: "bloodMagic/bloodRuneCarvedRadial",
		4: "bloodMagic/bloodRuneClassicPanel",
		5: "bloodMagic/bloodRuneTiles",
	},
	"bookshelf": {
		1: "bookshelf/rainbow",
		2: "bookshelf/necromancer-novice",
		3: "bookshelf/necromancer",
		4: "bookshelf/redtomes",
		5: "bookshelf/abandoned",
		6: "bookshelf/hoarder",
		7: "bookshelf/brim",
		8: "bookshelf/historician",
	},
	"brickCustom": {
		1: "brickCustom/large",
		2: "brickCustom/mortarless",
		3: "brickCustom/varied",
		5: "brickCustom/aged",
		6: "brickCustom/yellow",
	},
	"carpet": {
		0: "white",
		1: "orange",
		2: "lily",
		3: "lightblue",
		4: "yellow",
		5: "lightgreen",
		6: "pink",
		7: "darkgrey",
		8: "grey",
		9: "teal",
		10: "purple",
		11: "darkblue",
		12: "brown",
		13: "green",
		14: "red",
		15: "black",
	},
	"carpet_block": {
		0: "carpet/white",
		1: "carpet/orange",
		2: "carpet/lily",
		3: "carpet/lightblue",
		4: "carpet/yellow",
		5: "carpet/lightgreen",
		6: "carpet/pink",
		7: "carpet/darkgrey",
		8: "carpet/grey",
		9: "carpet/teal",
		10: "carpet/purple",
		11: "carpet/darkblue",
		12: "carpet/brown",
		13: "carpet/green",
		14: "carpet/red",
		15: "carpet/black",
	},
	"cloud": {
		0: "cloud/cloud",
		1: "cloud/large",
		2: "cloud/small",
		3: "cloud/vertical",
		4: "cloud/grid",
	},
	"cobblestone": {
		0: "cobblestone/terrain-cobb-brickaligned",
		1: "cobblestone/terrain-cob-detailedbrick",
		2: "cobblestone/terrain-cob-smallbrick",
		3: "cobblestone/terrain-cobblargetiledark",
		4: "cobblestone/terrain-cobbsmalltile",
		5: "cobblestone/terrain-cob-french",
		6: "cobblestone/terrain-cob-french2",
		7: "cobblestone/terrain-cobmoss-creepdungeon",
		8: "cobblestone/terrain-mossysmalltiledark",
		9: "cobblestone/terrain-pistonback-dungeontile",
		10: "cobblestone/terrain-pistonback-darkcreeper",
		11: "cobblestone/terrain-pistonback-darkdent",
		12: "cobblestone/terrain-pistonback-darkemboss",
		13: "cobblestone/terrain-pistonback-darkmarker",
		14: "cobblestone/terrain-pistonback-darkpanel",
	},
	"concrete": {
		0: "concrete/default",
		1: "concrete/block",
		2: "concrete/doubleslab",
		3: "concrete/blocks",
		4: "concrete/weathered",
		5: "concrete/weathered-block",
		6: "concrete/weathered-doubleslab",
		7: "concrete/weathered-blocks",
		8: "concrete/weathered-half",
		9: "concrete/weathered-block-half",
		10: "concrete/asphalt",
	},
	# Unlike every other group, Features$25.addBlocks() builds this one's 16 texture paths in a
	# loop ("cubit/" + i) instead of individual addVariation() calls with a literal string per
	# meta -- there's no per-meta string constant for javap to find, which is why the original
	# decompile pass missed it. Confirmed straight from the loop bytecode (bipush 16 bound) and
	# the jar's own assets/chisel/textures/blocks/cubit/0.png..15.png (2.12.3-GTNH).
	"cubit": {
		0: "0",
		1: "1",
		2: "2",
		3: "3",
		4: "4",
		5: "5",
		6: "6",
		7: "7",
		8: "8",
		9: "9",
		10: "10",
		11: "11",
		12: "12",
		13: "13",
		14: "14",
		15: "15",
	},
	"diamond": {
		1: "diamond/terrain-diamond-embossed",
		2: "diamond/terrain-diamond-gem",
		3: "diamond/terrain-diamond-cells",
		4: "diamond/terrain-diamond-space",
		5: "diamond/terrain-diamond-spaceblack",
		6: "diamond/terrain-diamond-simple",
		7: "diamond/terrain-diamond-bismuth",
		8: "diamond/terrain-diamond-crushed",
		9: "diamond/terrain-diamond-four",
		10: "diamond/terrain-diamond-fourornate",
		11: "diamond/terrain-diamond-zelda",
		12: "diamond/terrain-diamond-ornatelayer",
	},
	"diorite": {
		0: "diorite/diorite",
		1: "diorite/dioritePolished",
		2: "diorite/dioritePillar",
		3: "diorite/dioriteLBrick",
		4: "diorite/dioriteOrnate",
		5: "diorite/dioritePrism",
		6: "diorite/dioriteTiles",
	},
	"dirt": {
		0: "dirt/bricks",
		1: "dirt/netherbricks",
		2: "dirt/bricks3",
		3: "dirt/cobble",
		4: "dirt/reinforcedCobbleDirt",
		5: "dirt/reinforcedDirt",
		6: "dirt/happy",
		7: "dirt/bricks2",
		8: "dirt/bricks+dirt2",
		9: "dirt/hor",
		10: "dirt/vert",
		11: "dirt/layers",
		12: "dirt/vertical",
		13: "dirt/chunky",
		14: "dirt/horizontal",
		15: "dirt/plate",
	},
	"emerald": {
		1: "emerald/panel",
		2: "emerald/panelclassic",
		3: "emerald/smooth",
		4: "emerald/chunk",
		5: "emerald/goldborder",
		6: "emerald/zelda",
		7: "emerald/cell",
		8: "emerald/cellbismuth",
		9: "emerald/four",
		10: "emerald/fourornate",
		11: "emerald/ornate",
	},
	"end_Stone": {
		0: "endstone/end_bricks",
		1: "endstone/chaoticBricks",
		2: "endstone/CheckeredTile",
		3: "endstone/enderCircuit",
		4: "endstone/endFrenchBricks",
		5: "endstone/endPillar",
		6: "endstone/endStoneEtched",
		7: "endstone/prismaticEndStone",
		8: "endstone/endStoneChunk",
		9: "endstone/EnderFrame",
		10: "endstone/arcaneEndStone",
		11: "endstone/framedEndStone",
		12: "endstone/endStoneOrnate",
		13: "endstone/endStoneLargeTile",
	},
	"factory": {
		0: "factory/dots",
		1: "factory/rust2",
		2: "factory/rust",
		3: "factory/platex",
		4: "factory/wireframewhite",
		5: "factory/wireframe",
		6: "factory/hazard",
		7: "factory/hazardorange",
		8: "factory/circuit",
		9: "factory/metalbox",
		10: "factory/goldplate",
		11: "factory/goldplating",
		12: "factory/grinder",
		13: "factory/plating",
		14: "factory/rustplates",
		15: "factory/column",
	},
	"factory2": {
		0: "factory/iceiceice",
		1: "factory/vent",
		2: "factory/tilemosaic",
		3: "factory/wireframeblue",
	},
	"fantasyblock": {
		0: "fantasy/brick",
		1: "fantasy/brick-faded",
		2: "fantasy/brick-wear",
		3: "fantasy/bricks",
		4: "fantasy/decor",
		5: "fantasy/decor-block",
		6: "fantasy/pillar",
		7: "fantasy/pillar-decorated",
		8: "fantasy/gold-decor-1",
		9: "fantasy/gold-decor-2",
		10: "fantasy/gold-decor-3",
		11: "fantasy/gold-decor-4",
		12: "fantasy/plate",
		13: "fantasy/block",
		14: "fantasy/bricks-chaotic",
		15: "fantasy/bricks-wear",
	},
	"fantasyblock2": {
		0: "fantasy2/brick",
		1: "fantasy2/brick-faded",
		2: "fantasy2/brick-wear",
		3: "fantasy2/bricks",
		4: "fantasy2/decor",
		5: "fantasy2/decor-block",
		6: "fantasy2/pillar",
		7: "fantasy2/pillar-decorated",
		8: "fantasy2/gold-decor-1",
		9: "fantasy2/gold-decor-2",
		10: "fantasy2/gold-decor-3",
		11: "fantasy2/gold-decor-4",
		12: "fantasy2/plate",
		13: "fantasy2/block",
		14: "fantasy2/bricks-chaotic",
		15: "fantasy2/bricks-wear",
	},
	"futura": {
		0: "futura/WIP/screenMetallicWIP",
		1: "futura/WIP/screenCyanWIP",
		2: "futura/WIP/controller",
		3: "futura/WIP/wavyWIP",
		4: "futura/WIP/controllerPurple",
		5: "futura/WIP/uberWavy",
	},
	"glass": {
		1: "glass/terrain-glassbubble",
		2: "glass/terrain-glass-chinese",
		3: "glass/japanese",
		4: "glass/terrain-glassdungeon",
		5: "glass/terrain-glasslight",
		6: "glass/terrain-glassnoborder",
		7: "glass/terrain-glass-ornatesteel",
		8: "glass/terrain-glass-screen",
		9: "glass/terrain-glassshale",
		10: "glass/terrain-glass-steelframe",
		11: "glass/terrain-glassstone",
		12: "glass/terrain-glassstreak",
		13: "glass/terrain-glass-thickgrid",
		14: "glass/terrain-glass-thingrid",
		15: "glass/a1-glasswindow-ironfencemodern",
	},
	"glass2": {
		0: "glass/chrono",
	},
	"glass_pane": {
		1: "glasspane/terrain-glassbubble",
		2: "glasspane/terrain-glassnoborder",
		3: "glasspane/terrain-glass-screen",
		4: "glasspane/terrain-glassstreak",
		12: "glasspane/chinese",
		13: "glasspane/chinese2",
		14: "glasspane/japanese",
		15: "glasspane/japanese2",
	},
	# Registered through SubmapManagerSpecialMaterial(String.valueOf(i), MaterialType.GLOTEK):
	# registerIcons() builds "chisel:glotek/<i>-ctm" (the connected-texture sheet) and, separately,
	# "chisel:glotek/<i>" for the base icon -- both real files in the jar, and getBaseIcon() on the
	# latter's TextureSubmap returns it whole (no cropping), and it's a plain flat 16x16 PNG, so
	# it's exactly the base texture we need. Same story as "neonite" below (same render class,
	# different MaterialType) and the same shape as "cubit"/"sveltstone" above, just reached
	# through the connected-texture render path instead of a bare addVariation() call.
	"glotek": {
		0: "glotek/0",
		1: "glotek/1",
		2: "glotek/2",
		3: "glotek/3",
		4: "glotek/4",
		5: "glotek/5",
		6: "glotek/6",
		7: "glotek/7",
		8: "glotek/8",
		9: "glotek/9",
		10: "glotek/10",
		11: "glotek/11",
		12: "glotek/12",
		13: "glotek/13",
		14: "glotek/14",
		15: "glotek/15",
	},
	"gold": {
		1: "gold/terrain-gold-largeingot",
		2: "gold/terrain-gold-smallingot",
		3: "gold/terrain-gold-brick",
		4: "gold/terrain-gold-cart",
		5: "gold/terrain-gold-coin-heads",
		6: "gold/terrain-gold-coin-tails",
		7: "gold/terrain-gold-crate-dark",
		8: "gold/terrain-gold-crate-light",
		9: "gold/terrain-gold-plates",
		10: "gold/terrain-gold-rivets",
		11: "gold/terrain-gold-star",
		12: "gold/terrain-gold-space",
		13: "gold/terrain-gold-spaceblack",
		14: "gold/terrain-gold-simple",
	},
	"granite": {
		0: "granite/granite",
		1: "granite/granitePolished",
		2: "granite/granitePillar",
		3: "granite/graniteLBrick",
		4: "granite/graniteOrnate",
		5: "granite/granitePrism",
		6: "granite/graniteTiles",
	},
	"grimstone": {
		0: "grimstone/grimstone",
		1: "grimstone/smooth",
		2: "grimstone/hate",
		3: "grimstone/chiseled",
		4: "grimstone/blocks",
		5: "grimstone/blocks-rough",
		6: "grimstone/brick",
		7: "grimstone/largebricks",
		8: "grimstone/platform",
		9: "grimstone/platform-tiles",
		10: "grimstone/construction",
		11: "grimstone/fancy-tiles",
		12: "grimstone/plate",
		13: "grimstone/plate-rough",
		14: "grimstone/flaky",
	},
	"hellrock": {
		1: "netherrack/a1-netherrack-bloodgravel",
		2: "netherrack/a1-netherrack-bloodrock",
		3: "netherrack/a1-netherrack-bloodrockgrey",
		4: "netherrack/a1-netherrack-brinstar",
		5: "netherrack/a1-netherrack-brinstarshale",
		6: "netherrack/a1-netherrack-classic",
		7: "netherrack/a1-netherrack-classicspatter",
		8: "netherrack/a1-netherrack-guts",
		9: "netherrack/a1-netherrack-gutsdark",
		10: "netherrack/a1-netherrack-meat",
		11: "netherrack/a1-netherrack-meatred",
		12: "netherrack/a1-netherrack-meatrock",
		13: "netherrack/a1-netherrack-red",
		14: "netherrack/a1-netherrack-wells",
	},
	# Plain team.chisel.block.BlockCarvable (no glow/color/submap involved) -- Features$45's loop
	# builds "hempCrete/concrete/" + General.sGNames[i].replaceAll(" ", "").toLowerCase(), i.e.
	# the SAME vanilla dye-name array and transform as "woolenClay" below, just a different
	# texture subfolder. Real per-color 16x16 files confirmed in the jar for every meta.
	"hempcrete": {
		0: "hempCrete/concrete/white",
		1: "hempCrete/concrete/orange",
		2: "hempCrete/concrete/magenta",
		3: "hempCrete/concrete/lightblue",
		4: "hempCrete/concrete/yellow",
		5: "hempCrete/concrete/lime",
		6: "hempCrete/concrete/pink",
		7: "hempCrete/concrete/gray",
		8: "hempCrete/concrete/lightgray",
		9: "hempCrete/concrete/cyan",
		10: "hempCrete/concrete/purple",
		11: "hempCrete/concrete/blue",
		12: "hempCrete/concrete/brown",
		13: "hempCrete/concrete/green",
		14: "hempCrete/concrete/red",
		15: "hempCrete/concrete/black",
	},
	# Same class, same loop shape as "hempcrete" above (Features$46), just the "sand" subfolder.
	"hempcretesand": {
		0: "hempCrete/sand/white",
		1: "hempCrete/sand/orange",
		2: "hempCrete/sand/magenta",
		3: "hempCrete/sand/lightblue",
		4: "hempCrete/sand/yellow",
		5: "hempCrete/sand/lime",
		6: "hempCrete/sand/pink",
		7: "hempCrete/sand/gray",
		8: "hempCrete/sand/lightgray",
		9: "hempCrete/sand/cyan",
		10: "hempCrete/sand/purple",
		11: "hempCrete/sand/blue",
		12: "hempCrete/sand/brown",
		13: "hempCrete/sand/green",
		14: "hempCrete/sand/red",
		15: "hempCrete/sand/black",
	},
	# team.chisel.block.BlockCarvableGlow, not BlockCarvableColor -- unlike "antiBlock" above, all
	# 16 metas of Features$43's FIRST loop bind the exact same literal string ("hexPlating/hexBase")
	# as their addVariation() texture; only the .desc differs (reusing ItemDye.field_150921_b dye
	# names purely as flavor text for the tooltip, not as a real color). The visual difference
	# between metas is a glow-animation overlay (animations/archetype2) this importer doesn't
	# model, same as every other *_GLOW-family block -- so one shared flat texture across all 16
	# is the actual correct static appearance, not an approximation. hexBase.png is a real,
	# standalone 32x32 file (getBaseIcon() returns a submap's registered icon whole, uncropped, so
	# a larger-than-16x16 base tile is fine, same reasoning as "antiBlock" above).
	#
	# The class's SECOND block, "hexLargePlating", is deliberately left out: its addVariation call
	# uses the 4-arg (String, int, String, int) overload with a "hexPlating/hexNew" base name that
	# doesn't match any file in the jar (the real file is hexNew-v9.png) plus an extra i+20 index
	# argument -- almost certainly selecting a sub-icon some other way this table's simple
	# single-texture-per-meta shape can't express. Binding it wrong would be worse than dropping
	# it, same standard the rest of this file holds to.
	"hexPlating": {
		0: "hexPlating/hexBase",
		1: "hexPlating/hexBase",
		2: "hexPlating/hexBase",
		3: "hexPlating/hexBase",
		4: "hexPlating/hexBase",
		5: "hexPlating/hexBase",
		6: "hexPlating/hexBase",
		7: "hexPlating/hexBase",
		8: "hexPlating/hexBase",
		9: "hexPlating/hexBase",
		10: "hexPlating/hexBase",
		11: "hexPlating/hexBase",
		12: "hexPlating/hexBase",
		13: "hexPlating/hexBase",
		14: "hexPlating/hexBase",
		15: "hexPlating/hexBase",
	},
	"holystone": {
		0: "holystone/holystone",
		1: "holystone/smooth",
		2: "holystone/love",
		3: "holystone/chiseled",
		4: "holystone/blocks",
		5: "holystone/blocks-rough",
		6: "holystone/brick",
		7: "holystone/largebricks",
		8: "holystone/platform",
		9: "holystone/platform-tiles",
		10: "holystone/construction",
		11: "holystone/fancy-tiles",
		12: "holystone/plate",
		13: "holystone/plate-rough",
	},
	"ice": {
		1: "ice/a1-ice-light",
		2: "ice/a1-stonecobble-icecobble",
		3: "ice/a1-netherbrick-ice",
		4: "ice/a1-stonecobble-icebrick",
		5: "ice/a1-stonecobble-icebricksmall",
		6: "ice/a1-stonecobble-icedungeon",
		7: "ice/a1-stonecobble-icefour",
		8: "ice/a1-stonecobble-icefrench",
		9: "ice/sunkentiles",
		10: "ice/tiles",
		11: "ice/a1-stonecobble-icepanel",
		12: "ice/a1-stoneslab-ice",
		13: "ice/zelda",
		14: "ice/bismuth",
		15: "ice/poison",
	},
	"icePillar": {
		0: "icepillar/plainplain",
		1: "icepillar/plaingreek",
		2: "icepillar/greekplain",
		3: "icepillar/greekgreek",
		4: "icepillar/convexplain",
		5: "icepillar/carved",
		6: "icepillar/ornamental",
	},
	"ice_stairs": {
		1: "ice/a1-ice-light",
		2: "ice/a1-stonecobble-icecobble",
		3: "ice/a1-netherbrick-ice",
		4: "ice/a1-stonecobble-icebrick",
		5: "ice/a1-stonecobble-icebricksmall",
		6: "ice/a1-stonecobble-icedungeon",
		7: "ice/a1-stonecobble-icefour",
		8: "ice/a1-stonecobble-icefrench",
		9: "ice/sunkentiles",
		10: "ice/tiles",
		11: "ice/a1-stonecobble-icepanel",
		12: "ice/a1-stoneslab-ice",
		13: "ice/zelda",
		14: "ice/bismuth",
		15: "ice/poison",
	},
	"imperial": {
		0: "military/imperialCamo",
		1: "military/imperialCamoSecluded",
		2: "military/imperialPlate",
		3: "military/imperialCautionWhite",
		4: "military/imperialCautionOrange",
	},
	"iron": {
		1: "iron/terrain-iron-largeingot",
		2: "iron/terrain-iron-smallingot",
		3: "iron/terrain-iron-gears",
		4: "iron/terrain-iron-brick",
		5: "iron/terrain-iron-plates",
		6: "iron/terrain-iron-rivets",
		7: "iron/terrain-iron-coin-heads",
		8: "iron/terrain-iron-coin-tails",
		9: "iron/terrain-iron-crate-dark",
		10: "iron/terrain-iron-crate-light",
		11: "iron/terrain-iron-moon",
		12: "iron/terrain-iron-space",
		13: "iron/terrain-iron-spaceblack",
		14: "iron/terrain-iron-vents",
		15: "iron/terrain-iron-simple",
	},
	"iron_bars": {
		1: "ironpane/fenceIron",
		2: "ironpane/barbedwire",
		3: "ironpane/cage",
		4: "ironpane/fenceIronTop",
		5: "ironpane/terrain-glass-thickgrid",
		6: "ironpane/terrain-glass-thingrid",
		7: "ironpane/terrain-glass-ornatesteel",
		8: "ironpane/bars",
		9: "ironpane/spikes",
	},
	"laboratory": {
		0: "laboratory/wallpanel",
		1: "laboratory/dottedpanel",
		2: "laboratory/largewall",
		3: "laboratory/roundel",
		4: "laboratory/wallvents",
		5: "laboratory/largetile",
		6: "laboratory/smalltile",
		7: "laboratory/floortile",
		8: "laboratory/checkertile",
		9: "laboratory/clearscreen",
		10: "laboratory/fuzzscreen",
		11: "laboratory/largesteel",
		12: "laboratory/smallsteel",
		13: "laboratory/directionright",
		14: "laboratory/directionleft",
		15: "laboratory/infocon",
	},
	"lapis": {
		1: "lapis/terrain-lapisblock-chunky",
		2: "lapis/terrain-lapisblock-panel",
		3: "lapis/terrain-lapisblock-zelda",
		4: "lapis/terrain-lapisornate",
		5: "lapis/terrain-lapistile",
		6: "lapis/a1-blocklapis-panel",
		7: "lapis/a1-blocklapis-smooth",
		8: "lapis/a1-blocklapis-ornatelayer",
	},
	"lavastone": {
		0: "lavastone/cobble",
		1: "lavastone/black",
		2: "lavastone/tiles",
		3: "lavastone/chaotic",
		4: "lavastone/creeper",
		5: "lavastone/panel",
		6: "lavastone/panel-ornate",
		7: "lavastone/dark",
	},
	"leaves": {
		6: "leaves/dead",
		7: "leaves/fancy",
		8: "leaves/pinkpetal",
		9: "leaves/red_roses",
		10: "leaves/roses",
		11: "leaves/christmasBalls",
		12: "leaves/christmasLights",
	},
	"lightstone": {
		1: "lightstone/terrain-sulphur-cobble",
		2: "lightstone/terrain-sulphur-corroded",
		3: "lightstone/terrain-sulphur-glass",
		4: "lightstone/terrain-sulphur-neon",
		5: "lightstone/terrain-sulphur-ornate",
		6: "lightstone/terrain-sulphur-rocky",
		7: "lightstone/terrain-sulphur-shale",
		8: "lightstone/terrain-sulphur-tile",
		9: "lightstone/terrain-sulphur-weavelanternlight",
		10: "lightstone/a1-glowstone-cobble",
		11: "lightstone/a1-glowstone-growth",
		12: "lightstone/a1-glowstone-layers",
		13: "lightstone/a1-glowstone-tilecorroded",
		14: "lightstone/glowstone-bismuth",
		15: "lightstone/glowstone-bismuth-panel",
	},
	"limestone": {
		0: "limestone",
		1: "limestone/terrain-cobbsmalltilelight",
		2: "limestone/terrain-cob-frenchlight",
		3: "limestone/terrain-cob-french2light",
		4: "limestone/terrain-cobmoss-creepdungeonlight",
		5: "limestone/terrain-cob-smallbricklight",
		6: "limestone/terrain-mossysmalltilelight",
		7: "limestone/terrain-pistonback-dungeon",
		8: "limestone/terrain-pistonback-dungeonornate",
		9: "limestone/terrain-pistonback-dungeonvent",
		10: "limestone/terrain-pistonback-lightcreeper",
		11: "limestone/terrain-pistonback-lightdent",
		12: "limestone/terrain-pistonback-lightemboss",
		13: "limestone/terrain-pistonback-lightfour",
		14: "limestone/terrain-pistonback-lightmarker",
		15: "limestone/terrain-pistonback-lightpanel",
	},
	"limestoneSlab": {
		0: "limestone",
		1: "limestone/terrain-cobbsmalltilelight",
		2: "limestone/terrain-cob-frenchlight",
		3: "limestone/terrain-cob-french2light",
		4: "limestone/terrain-cobmoss-creepdungeonlight",
		5: "limestone/terrain-cob-smallbricklight",
		6: "limestone/terrain-mossysmalltilelight",
		7: "limestone/terrain-pistonback-dungeon",
		8: "limestone/terrain-pistonback-dungeonornate",
		9: "limestone/terrain-pistonback-dungeonvent",
		10: "limestone/terrain-pistonback-lightcreeper",
		11: "limestone/terrain-pistonback-lightdent",
		12: "limestone/terrain-pistonback-lightemboss",
		13: "limestone/terrain-pistonback-lightfour",
		14: "limestone/terrain-pistonback-lightmarker",
		15: "limestone/terrain-pistonback-lightpanel",
	},
	"limestoneStairs": {
		0: "limestone",
		1: "limestone/terrain-cobbsmalltilelight",
		2: "limestone/terrain-cob-frenchlight",
		3: "limestone/terrain-cob-french2light",
		4: "limestone/terrain-cobmoss-creepdungeonlight",
		5: "limestone/terrain-cob-smallbricklight",
		6: "limestone/terrain-mossysmalltilelight",
		7: "limestone/terrain-pistonback-dungeon",
		8: "limestone/terrain-pistonback-dungeonornate",
		9: "limestone/terrain-pistonback-dungeonvent",
		10: "limestone/terrain-pistonback-lightcreeper",
		11: "limestone/terrain-pistonback-lightdent",
		12: "limestone/terrain-pistonback-lightemboss",
		13: "limestone/terrain-pistonback-lightfour",
		14: "limestone/terrain-pistonback-lightmarker",
		15: "limestone/terrain-pistonback-lightpanel",
	},
	"marble": {
		0: "marble",
		1: "marble/a1-stoneornamental-marblebrick",
		2: "marble/a1-stoneornamental-marbleclassicpanel",
		3: "marble/a1-stoneornamental-marbleornate",
		4: "marble/panel",
		5: "marble/block",
		6: "marble/terrain-pistonback-marblecreeperdark",
		7: "marble/terrain-pistonback-marblecreeperlight",
		8: "marble/a1-stoneornamental-marblecarved",
		9: "marble/a1-stoneornamental-marblecarvedradial",
		10: "marble/terrain-pistonback-marbledent",
		11: "marble/terrain-pistonback-marbledent-small",
		12: "marble/marble-bricks",
		13: "marble/marble-arranged-bricks",
		14: "marble/marble-fancy-bricks",
		15: "marble/marble-blocks",
	},
	"marblePillar": {
		0: "marblepillar/pillar",
		1: "marblepillar/default",
		2: "marblepillar/simple",
		3: "marblepillar/convex",
		4: "marblepillar/rough",
		5: "marblepillar/greekdecor",
		6: "marblepillar/greekgreek",
		7: "marblepillar/greekplain",
		8: "marblepillar/plaindecor",
		9: "marblepillar/plaingreek",
		10: "marblepillar/plainplain",
		11: "marblepillar/widedecor",
		12: "marblepillar/widegreek",
		13: "marblepillar/wideplain",
		14: "marblepillar/carved",
		15: "marblepillar/ornamental",
	},
	"marblePillarOld": {
		0: "marblepillarold/column",
		1: "marblepillarold/capstone",
		2: "marblepillarold/base",
		3: "marblepillarold/small",
		4: "marblepillarold/pillar-carved",
		5: "marblepillarold/a1-stoneornamental-marblegreek",
		6: "marblepillarold/a1-stonepillar-greek",
		7: "marblepillarold/a1-stonepillar-plain",
		8: "marblepillarold/a1-stonepillar-greektopplain",
		9: "marblepillarold/a1-stonepillar-plaintopplain",
		10: "marblepillarold/a1-stonepillar-greekbottomplain",
		11: "marblepillarold/a1-stonepillar-plainbottomplain",
		12: "marblepillarold/a1-stonepillar-greektopgreek",
		13: "marblepillarold/a1-stonepillar-plaintopgreek",
		14: "marblepillarold/a1-stonepillar-greekbottomgreek",
		15: "marblepillarold/a1-stonepillar-plainbottomgreek",
	},
	"marblePillarSlab": {
		0: "marblepillarslab/pillar",
		1: "marblepillarslab/default",
		2: "marblepillarslab/simple",
		3: "marblepillarslab/convex",
		4: "marblepillarslab/rough",
		5: "marblepillarslab/greekdecor",
		6: "marblepillarslab/greekgreek",
		7: "marblepillarslab/greekplain",
		8: "marblepillarslab/plaindecor",
		9: "marblepillarslab/plaingreek",
		10: "marblepillarslab/plainplain",
		11: "marblepillarslab/widedecor",
		12: "marblepillarslab/widegreek",
		13: "marblepillarslab/wideplain",
		14: "marblepillarslab/carved",
		15: "marblepillarslab/ornamental",
	},
	"marblePillarSlabOld": {
		0: "marblepillarslabold/column",
		1: "marblepillarslabold/capstone",
		2: "marblepillarslabold/base",
		3: "marblepillarslabold/small",
		4: "marblepillarslabold/pillar-carved",
		5: "marblepillarslabold/a1-stoneornamental-marblegreek",
		6: "marblepillarslabold/a1-stonepillar-greek",
		7: "marblepillarslabold/a1-stonepillar-plain",
		8: "marblepillarslabold/a1-stonepillar-greektopplain",
		9: "marblepillarslabold/a1-stonepillar-plaintopplain",
		10: "marblepillarslabold/a1-stonepillar-greekbottomplain",
		11: "marblepillarslabold/a1-stonepillar-plainbottomplain",
		12: "marblepillarslabold/a1-stonepillar-greektopgreek",
		13: "marblepillarslabold/a1-stonepillar-plaintopgreek",
		14: "marblepillarslabold/a1-stonepillar-greekbottomgreek",
		15: "marblepillarslabold/a1-stonepillar-plainbottomgreek",
	},
	"marbleSlab": {
		0: "marble",
		1: "marbleslab/a1-stoneornamental-marblebrick",
		2: "marbleslab/a1-stoneornamental-marbleclassicpanel",
		3: "marbleslab/a1-stoneornamental-marbleornate",
		4: "marbleslab/a1-stoneornamental-marblepanel",
		5: "marbleslab/terrain-pistonback-marble",
		6: "marbleslab/terrain-pistonback-marblecreeperdark",
		7: "marbleslab/terrain-pistonback-marblecreeperlight",
		8: "marbleslab/a1-stoneornamental-marblecarved",
		9: "marbleslab/a1-stoneornamental-marblecarvedradial",
		10: "marbleslab/terrain-pistonback-marbledent",
		11: "marbleslab/terrain-pistonback-marbledent-small",
		12: "marbleslab/marble-bricks",
		13: "marbleslab/marble-arranged-bricks",
		14: "marbleslab/marble-fancy-bricks",
		15: "marbleslab/marble-blocks",
	},
	"marbleStairs": {
		0: "marble",
		2: "marbleslab/a1-stoneornamental-marbleclassicpanel",
		3: "marbleslab/a1-stoneornamental-marbleornate",
		4: "marbleslab/a1-stoneornamental-marblepanel",
		5: "marbleslab/terrain-pistonback-marble",
		6: "marbleslab/terrain-pistonback-marblecreeperdark",
		7: "marbleslab/terrain-pistonback-marblecreeperlight",
		8: "marbleslab/a1-stoneornamental-marblecarved",
		9: "marbleslab/a1-stoneornamental-marblecarvedradial",
		10: "marbleslab/terrain-pistonback-marbledent",
		11: "marbleslab/terrain-pistonback-marbledent-small",
		12: "marbleslab/marble-bricks",
		13: "marbleslab/marble-arranged-bricks",
		14: "marbleslab/marble-fancy-bricks",
		15: "marbleslab/marble-blocks",
	},
	"mossy_templeblock": {
		0: "templemossy/cobble",
		1: "templemossy/ornate",
		2: "templemossy/plate",
		3: "templemossy/plate-cracked",
		4: "templemossy/bricks",
		5: "templemossy/bricks-large",
		6: "templemossy/bricks-weared",
		7: "templemossy/bricks-disarray",
		8: "templemossy/column",
		9: "templemossy/stand",
		10: "templemossy/stand-mosaic",
		11: "templemossy/stand-creeper",
		12: "templemossy/tiles",
		13: "templemossy/smalltiles",
		14: "templemossy/tiles-light",
		15: "templemossy/smalltiles-light",
	},
	# Same SubmapManagerSpecialMaterial shape as "glotek" above (Features$62, MaterialType.NEONITE)
	# -- "chisel:neonite/<i>" is a plain flat 16x16 base icon, "<i>-ctm" the connected-texture
	# sheet we don't need.
	"neonite": {
		0: "neonite/0",
		1: "neonite/1",
		2: "neonite/2",
		3: "neonite/3",
		4: "neonite/4",
		5: "neonite/5",
		6: "neonite/6",
		7: "neonite/7",
		8: "neonite/8",
		9: "neonite/9",
		10: "neonite/10",
		11: "neonite/11",
		12: "neonite/12",
		13: "neonite/13",
		14: "neonite/14",
		15: "neonite/15",
	},
	"netherBrick": {
		1: "netherbrick/a1-netherbrick-brinstar",
		2: "netherbrick/a1-netherbrick-classicspatter",
		3: "netherbrick/a1-netherbrick-guts",
		4: "netherbrick/a1-netherbrick-gutsdark",
		5: "netherbrick/a1-netherbrick-gutssmall",
		6: "netherbrick/a1-netherbrick-lavabrinstar",
		7: "netherbrick/a1-netherbrick-lavabrown",
		8: "netherbrick/a1-netherbrick-lavaobsidian",
		9: "netherbrick/a1-netherbrick-lavastonedark",
		10: "netherbrick/a1-netherbrick-meat",
		11: "netherbrick/a1-netherbrick-meatred",
		12: "netherbrick/a1-netherbrick-meatredsmall",
		13: "netherbrick/a1-netherbrick-meatsmall",
		14: "netherbrick/a1-netherbrick-red",
		15: "netherbrick/a1-netherbrick-redsmall",
	},
	"nucrete": {
		0: "nucrete/darkbreezeblock",
		1: "nucrete/darkpanel",
		2: "nucrete/darkpanel2",
		3: "nucrete/darksmooth",
		4: "nucrete/darkstamped",
		5: "nucrete/darkstrip",
		6: "nucrete/darkstripes",
		7: "nucrete/darktiles",
		8: "nucrete/lightbreezeblocks",
		9: "nucrete/lightpanel",
		10: "nucrete/lightpanel2",
		11: "nucrete/lightsmooth",
		12: "nucrete/lightstamped",
		13: "nucrete/lightstrip",
		14: "nucrete/lightstripe",
		15: "nucrete/lighttiles",
	},
	"obsidian": {
		1: "obsidian/pillar",
		2: "obsidian/pillar-quartz",
		3: "obsidian/chiseled",
		4: "obsidian/panel-shiny",
		5: "obsidian/panel",
		6: "obsidian/chunks",
		7: "obsidian/growth",
		8: "obsidian/crystal",
		9: "obsidian/map-a",
		10: "obsidian/map-b",
		11: "obsidian/panel-light",
		12: "obsidian/blocks",
		13: "obsidian/tiles",
		14: "obsidian/greek",
		15: "obsidian/crate",
	},
	"packedice": {
		1: "ice/a1-ice-light",
		2: "ice/a1-stonecobble-icecobble",
		3: "ice/a1-netherbrick-ice",
		4: "ice/a1-stonecobble-icebrick",
		5: "ice/a1-stonecobble-icebricksmall",
		6: "ice/a1-stonecobble-icedungeon",
		7: "ice/a1-stonecobble-icefour",
		8: "ice/a1-stonecobble-icefrench",
		9: "ice/sunkentiles",
		10: "ice/tiles",
		11: "ice/a1-stonecobble-icepanel",
		12: "ice/a1-stoneslab-ice",
		13: "ice/zelda",
		14: "ice/bismuth",
		15: "ice/poison",
	},
	"packedice_pillar": {
		0: "icepillar/plainplain",
		1: "icepillar/plaingreek",
		2: "icepillar/greekplain",
		3: "icepillar/greekgreek",
		4: "icepillar/convexplain",
		5: "icepillar/carved",
		6: "icepillar/ornamental",
	},
	"packedice_stairs": {
		1: "ice/a1-ice-light",
		2: "ice/a1-stonecobble-icecobble",
		3: "ice/a1-netherbrick-ice",
		4: "ice/a1-stonecobble-icebrick",
		5: "ice/a1-stonecobble-icebricksmall",
		6: "ice/a1-stonecobble-icedungeon",
		7: "ice/a1-stonecobble-icefour",
		8: "ice/a1-stonecobble-icefrench",
		9: "ice/sunkentiles",
		10: "ice/tiles",
		11: "ice/a1-stonecobble-icepanel",
		12: "ice/a1-stoneslab-ice",
		13: "ice/zelda",
		14: "ice/bismuth",
		15: "ice/poison",
	},
	"paperwall": {
		0: "paper/box",
		1: "paper/throughMiddle",
		2: "paper/cross",
		3: "paper/sixSections",
		4: "paper/vertical",
		5: "paper/horizontal",
		6: "paper/floral",
		7: "paper/plain",
		8: "paper/door",
	},
	"purpur": {
		0: "end_purpur/purpur_block",
		1: "end_purpur/purpur_pillar",
		2: "end_purpur/shulker",
		3: "end_purpur/tilePurpur",
		4: "end_purpur/tileBrokenPurpur",
		5: "end_purpur/prismaticPurpur",
		6: "end_purpur/purpurBricks",
		7: "end_purpur/purpurCobble",
		8: "end_purpur/arcanePurpur",
		9: "end_purpur/purpurLargeTile",
		10: "end_purpur/purpurOrnate",
	},
	"rebel": {
		0: "military/rebelCamo",
		1: "military/rebelCamoSecluded",
		2: "military/rebelPlate",
		3: "military/rebelCautionWhite",
		4: "military/rebelCautionRed",
	},
	"redstone_block": {
		1: "redstone/smooth",
		2: "redstone/block",
		3: "redstone/blocks",
		4: "redstone/bricks",
		5: "redstone/smallbricks",
		6: "redstone/smallchaotic",
		7: "redstone/chiseled",
		8: "redstone/ere",
		9: "redstone/ornate-tiles",
		10: "redstone/pillar",
		11: "redstone/tiles",
		12: "redstone/circuit",
		13: "redstone/supaplex",
		14: "redstone/a1-blockredstone-skullred",
		15: "redstone/a1-blockredstone-redstonezelda",
	},
	"roadLine": {
		0: "line-marking/white-center",
		1: "line-marking/double-white-center",
		2: "line-marking/yellow-center",
		3: "line-marking/double-yellow-center",
		4: "line-marking/warning-center",
	},
	"sandstone": {
		0: "sandstone/terrain-sandstone-smoothglyph",
		1: "sandstone/terrain-sandstone-solidcobble",
		2: "sandstone/a0-sandstonepreview-boxcreeper",
		3: "sandstone/faded",
		4: "sandstone/column",
		5: "sandstone/capstone",
		6: "sandstone/small",
		7: "sandstone/base",
		8: "sandstone/smooth",
		9: "sandstone/smooth-cap",
		10: "sandstone/smooth-small",
		11: "sandstone/smooth-base",
		12: "sandstone/block",
		13: "sandstone/blocks",
		14: "sandstone/mosaic",
		15: "sandstone/horizontal-tiles",
		16: "sandstone2/terrain-sandstone-brickflat",
		17: "sandstone2/a0-sandstonepreview-smoothflat",
	},
	"stoneMoss": {
		1: "cobblestonemossy/terrain-cobb-brickaligned",
		2: "cobblestonemossy/terrain-cob-detailedbrick",
		3: "cobblestonemossy/terrain-cob-smallbrick",
		4: "cobblestonemossy/terrain-cobblargetiledark",
		5: "cobblestonemossy/terrain-cobbsmalltile",
		6: "cobblestonemossy/terrain-cob-french",
		7: "cobblestonemossy/terrain-cob-french2",
		8: "cobblestonemossy/terrain-cobmoss-creepdungeon",
		9: "cobblestonemossy/terrain-mossysmalltiledark",
		10: "cobblestonemossy/terrain-pistonback-dungeontile",
		11: "cobblestonemossy/terrain-pistonback-darkcreeper",
		12: "cobblestonemossy/terrain-pistonback-darkdent",
		13: "cobblestonemossy/terrain-pistonback-darkemboss",
		14: "cobblestonemossy/terrain-pistonback-darkmarker",
		15: "cobblestonemossy/terrain-pistonback-darkpanel",
	},
	"stonebricksmooth": {
		0: "stonebrick2/masonBricksPlain",
		1: "stonebrick2/masonBricksFelsic",
		2: "stonebrick2/masonBricksMafic",
		3: "stonebrick2/masonBricksMixed",
		4: "stonebrick/smallbricks",
		5: "stonebrick/largebricks",
		6: "stonebrick/smallchaotic",
		7: "stonebrick/chaoticbricks",
		8: "stonebrick/chaotic",
		9: "stonebrick/fancy",
		10: "stonebrick/ornate",
		11: "stonebrick/largeornate",
		12: "stonebrick/panel-hard",
		13: "stonebrick/sunken",
		14: "stonebrick/ornatepanel",
		15: "stonebrick/poison",
	},
	# Same loop-generated shape as "cubit" above (Features$92.addBlocks(), "sveltstone/" + i) --
	# missed by the original decompile for the same reason. Confirmed against the loop bytecode
	# and assets/chisel/textures/blocks/sveltstone/0.png..15.png; display names come straight
	# from the jar's own en_US.lang (tile.sveltstone.<n>.desc), same as any other group.
	"sveltstone": {
		0: "0",
		1: "1",
		2: "2",
		3: "3",
		4: "4",
		5: "5",
		6: "6",
		7: "7",
		8: "8",
		9: "9",
		10: "10",
		11: "11",
		12: "12",
		13: "13",
		14: "14",
		15: "15",
	},
	"technical": {
		0: "technical/scaffoldTransparent",
		1: "technical/cautiontape",
		2: "technical/industrialrelic",
		3: "technical/pipesLarge",
		4: "technical/fanFastTransparent",
		5: "technical/pipesSmall",
		6: "technical/fanStillTransparent",
		7: "technical/vent",
		8: "technical/ventGlowing",
		9: "technical/insulationv2",
		10: "technical/spinningStuffAnim",
		11: "technical/cables",
		12: "technical/rustyBoltedPlates",
		13: "technical/grate",
		14: "technical/fanStillTransparent",
		15: "technical/grateRusty",
	},
	"technical3": {
		0: "technical/massiveFan",
		1: "technical/massiveHexPlating",
	},
	"technical4": {
		0: "technical/new/weatheredGreenPanels",
		1: "technical/new/weatheredOrangePanels",
		2: "technical/new/Sturdy",
		3: "technical/new/MegaCell",
		4: "technical/new/ExhaustPlating",
		5: "technical/new/MakeshiftPanels",
		6: "technical/new/Piping",
		7: "technical/new/concrete/concreteBlocks",
	},
	"templeblock": {
		0: "temple/cobble",
		1: "temple/ornate",
		2: "temple/plate",
		3: "temple/plate-cracked",
		4: "temple/bricks",
		5: "temple/bricks-large",
		6: "temple/bricks-weared",
		7: "temple/bricks-disarray",
		8: "temple/column",
		9: "temple/stand",
		10: "temple/stand-mosaic",
		11: "temple/stand-creeper",
		12: "temple/tiles",
		13: "temple/smalltiles",
		14: "temple/tiles-light",
		15: "temple/smalltiles-light",
	},
	"thaumium": {
		0: "thaumium/ornate",
		1: "thaumium/totem",
		2: "thaumium/thaumiumBigBricks",
		3: "thaumium/small",
		4: "thaumium/lattice",
		5: "thaumium/planks",
	},
	"tyrian": {
		0: "tyrian/shining",
		1: "tyrian/tyrian",
		2: "tyrian/chaotic",
		3: "tyrian/softplate",
		4: "tyrian/rust",
		5: "tyrian/elaborate",
		6: "tyrian/routes",
		7: "tyrian/platform",
		8: "tyrian/platetiles",
		9: "tyrian/diagonal",
		10: "tyrian/dent",
		11: "tyrian/blueplating",
		12: "tyrian/black",
		13: "tyrian/black2",
		14: "tyrian/opening",
		15: "tyrian/plate",
	},
	"valentines": {
		0: "valentines/1",
		1: "valentines/companion",
		2: "valentines/2",
		3: "valentines/3",
		4: "valentines/4",
		5: "valentines/5",
		6: "valentines/6",
		7: "valentines/7",
		8: "valentines/8",
		9: "valentines/9",
	},
	"voidstonePillar": {
		0: "voidstone/pillar",
	},
	"voidstonePillar2": {
		0: "voidstone/animated/pillar",
	},
	"warningSign": {
		0: "warning/rad",
		1: "warning/bio",
		2: "warning/fire",
		3: "warning/explosion",
		4: "warning/death",
		5: "warning/falling",
		6: "warning/fall",
		7: "warning/voltage",
		8: "warning/generic",
		9: "warning/acid",
		10: "warning/underconstruction",
		11: "warning/sound",
		12: "warning/noentry",
		13: "warning/cryogenic",
		14: "warning/oxygen",
	},
	"waterstone": {
		0: "waterstone/cobble",
		1: "waterstone/black",
		2: "waterstone/tiles",
		3: "waterstone/chaotic",
		4: "waterstone/creeper",
		5: "waterstone/panel",
		6: "waterstone/panel-ornate",
	},
	# Plain BlockCarvable (Features$111) -- General.sGNames[i].replaceAll(" ", "").toLowerCase()
	# under "woolenClay/", the same dye-name array and transform "hempcrete"/"hempcretesand" above
	# use. Registry is "woolen_clay" (confirmed from the class's own registerAll/registerOre
	# calls) even though the texture folder is camelCase "woolenClay" -- Chisel isn't internally
	# consistent about this, so the table key has to match the registry, not the folder.
	"woolen_clay": {
		0: "woolenClay/white",
		1: "woolenClay/orange",
		2: "woolenClay/magenta",
		3: "woolenClay/lightblue",
		4: "woolenClay/yellow",
		5: "woolenClay/lime",
		6: "woolenClay/pink",
		7: "woolenClay/gray",
		8: "woolenClay/lightgray",
		9: "woolenClay/cyan",
		10: "woolenClay/purple",
		11: "woolenClay/blue",
		12: "woolenClay/brown",
		13: "woolenClay/green",
		14: "woolenClay/red",
		15: "woolenClay/black",
	},
}
